services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: ems-mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"   # SMTP - ovde Spring Boot šalje mejlove
      - "8025:8025"   # Web UI - ovde pregledaš primljene mejlove
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: "true"
      MP_SMTP_AUTH_ALLOW_INSECURE: "true"
