-- Minimalna Oracle šema za PL/SQL modul (samostalno testiranje bez MySQL migracije).
-- Pokreni kao SYS ili korisnik sa DDL pravima, zatim ostale skripte iz database/oracle/.
-- Primer: sqlplus ems/ems@//localhost:1521/XEPDB1 @00_bootstrap_standalone.sql

WHENEVER SQLERROR EXIT SQL.SQLCODE

PROMPT === Brisanje objekata (idempotentno) ===
BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER trg_analiza_zabrana_brisanja';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER trg_analiza_validacija_iznosa';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP PACKAGE BODY paket_profit_menadzment';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP PACKAGE paket_profit_menadzment';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE dogadjaj_koordinator CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE analize_profitabilnosti CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE dogadjaj CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE zaposleni CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE korisnik CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE lokacija CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

PROMPT === Kreiranje tabela ===
CREATE TABLE lokacija (
    lokacija_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    naziv       VARCHAR2(200) NOT NULL
);

CREATE TABLE korisnik (
    korisnik_id          NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ime                  VARCHAR2(100) NOT NULL,
    prezime              VARCHAR2(100) NOT NULL,
    email                VARCHAR2(150) NOT NULL UNIQUE,
    lozinka_hash         VARCHAR2(255) NOT NULL,
    tip_korisnika        VARCHAR2(30) NOT NULL,
    status               VARCHAR2(20) DEFAULT 'AKTIVAN' NOT NULL
);

CREATE TABLE zaposleni (
    korisnik_id NUMBER(19) PRIMARY KEY,
    uloga       VARCHAR2(30) NOT NULL,
    CONSTRAINT fk_zap_kor FOREIGN KEY (korisnik_id) REFERENCES korisnik(korisnik_id)
);

CREATE TABLE dogadjaj (
    dogadjaj_id      NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    lokacija_id      NUMBER(19) NOT NULL,
    naziv            VARCHAR2(200) NOT NULL,
    datum_pocetka    DATE NOT NULL,
    datum_zavrsetka  DATE NOT NULL,
    maks_kapacitet   NUMBER(10) NOT NULL,
    status           VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
    CONSTRAINT fk_dog_lok FOREIGN KEY (lokacija_id) REFERENCES lokacija(lokacija_id)
);

CREATE TABLE analize_profitabilnosti (
    analiza_id      NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    dogadjaj_id     NUMBER(19) NOT NULL,
    kreirao_id      NUMBER(19) NOT NULL,
    ukupan_prihod   NUMBER(15,2) DEFAULT 0 NOT NULL,
    ukupan_trosak   NUMBER(15,2) DEFAULT 0 NOT NULL,
    datum_analize   DATE DEFAULT SYSDATE NOT NULL,
    finalizovano_at TIMESTAMP,
    rezultat_ocene  VARCHAR2(20),
    status          VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
    napomene        CLOB,
    CONSTRAINT fk_ap_dog FOREIGN KEY (dogadjaj_id) REFERENCES dogadjaj(dogadjaj_id),
    CONSTRAINT fk_ap_kreirao FOREIGN KEY (kreirao_id) REFERENCES zaposleni(korisnik_id),
    CONSTRAINT chk_ap_iznosi CHECK (ukupan_prihod >= 0 AND ukupan_trosak >= 0)
);

PROMPT === Demo podaci ===
INSERT INTO lokacija (naziv) VALUES ('Demo lokacija Beograd');

INSERT INTO korisnik (ime, prezime, email, lozinka_hash, tip_korisnika)
VALUES ('Fin', 'Kontrolor', 'fin.plsql@demo.local', 'hash', 'ZAPOSLENI');
INSERT INTO zaposleni (korisnik_id, uloga)
VALUES ((SELECT korisnik_id FROM korisnik WHERE email = 'fin.plsql@demo.local'), 'FINANSIJSKI_KONTROLOR');

INSERT INTO korisnik (ime, prezime, email, lozinka_hash, tip_korisnika)
VALUES ('Petar', 'Program', 'program.plsql@demo.local', 'hash', 'ZAPOSLENI');
INSERT INTO zaposleni (korisnik_id, uloga)
VALUES ((SELECT korisnik_id FROM korisnik WHERE email = 'program.plsql@demo.local'), 'KOORDINATOR_PROGRAMA');

INSERT INTO korisnik (ime, prezime, email, lozinka_hash, tip_korisnika)
VALUES ('Jelena', 'Resursi', 'resursi.plsql@demo.local', 'hash', 'ZAPOSLENI');
INSERT INTO zaposleni (korisnik_id, uloga)
VALUES ((SELECT korisnik_id FROM korisnik WHERE email = 'resursi.plsql@demo.local'), 'KOORDINATOR_RESURSA');

INSERT INTO dogadjaj (lokacija_id, naziv, datum_pocetka, datum_zavrsetka, maks_kapacitet, status)
VALUES (
    (SELECT lokacija_id FROM lokacija WHERE ROWNUM = 1),
    'PL/SQL Demo Konferencija',
    DATE '2026-06-01',
    DATE '2026-06-03',
    500,
    'ZAVRSEN'
);

INSERT INTO analize_profitabilnosti (
    dogadjaj_id, kreirao_id, ukupan_prihod, ukupan_trosak,
    datum_analize, status, rezultat_ocene, finalizovano_at, napomene
) VALUES (
    (SELECT dogadjaj_id FROM dogadjaj WHERE naziv = 'PL/SQL Demo Konferencija'),
    (SELECT korisnik_id FROM korisnik WHERE email = 'fin.plsql@demo.local'),
    440000, 113000, DATE '2026-06-10', 'FINALIZOVANA', 'PROFITABILAN', SYSTIMESTAMP,
    'Demo visoko profitabilna analiza'
);

INSERT INTO analize_profitabilnosti (
    dogadjaj_id, kreirao_id, ukupan_prihod, ukupan_trosak,
    datum_analize, status, rezultat_ocene
) VALUES (
    (SELECT dogadjaj_id FROM dogadjaj WHERE naziv = 'PL/SQL Demo Konferencija'),
    (SELECT korisnik_id FROM korisnik WHERE email = 'fin.plsql@demo.local'),
    165000, 245000, DATE '2026-06-11', 'DRAFT', 'GUBITAK'
);

COMMIT;
PROMPT === Bootstrap završen ===
