-- F3 modul: tabele budzeta i troskova (FK na postojecu dogadjaj).

WHENEVER SQLERROR EXIT SQL.SQLCODE
PROMPT === F3 CREATE TABLES ===

CREATE TABLE budzet_kategorije (
    kategorija_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    naziv         VARCHAR2(255) NOT NULL,
    CONSTRAINT uk_budzet_kat_naziv UNIQUE (naziv)
);

CREATE TABLE budzeti (
    budzet_id       NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    dogadjaj_id     NUMBER(19) NOT NULL,
    naziv_budzeta   VARCHAR2(255) NOT NULL,
    planirani_iznos NUMBER(15,2) NOT NULL,
    odobreni_iznos  NUMBER(15,2) NOT NULL,
    status          VARCHAR2(16) DEFAULT 'DRAFT' NOT NULL,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_budzet_dogadjaj FOREIGN KEY (dogadjaj_id) REFERENCES dogadjaj(dogadjaj_id),
    CONSTRAINT chk_budzet_iznosi CHECK (planirani_iznos >= 0 AND odobreni_iznos >= 0)
);

CREATE TABLE stavke_budzeta (
    budzet_id         NUMBER(19) NOT NULL,
    kategorija_id     NUMBER(19) NOT NULL,
    planirani_iznos   NUMBER(15,2) NOT NULL,
    stvarni_iznos     NUMBER(15,2) DEFAULT 0 NOT NULL,
    prag_upozorenja   NUMBER(5,4) DEFAULT 0.8000 NOT NULL,
    prag_kriticnog    NUMBER(5,4) DEFAULT 0.9500 NOT NULL,
    status_kontrole   VARCHAR2(16) DEFAULT 'NA_PLANU' NOT NULL,
    last_alert_level  VARCHAR2(16) DEFAULT 'NONE' NOT NULL,
    komentar          VARCHAR2(500),
    CONSTRAINT pk_stavke_budzeta PRIMARY KEY (budzet_id, kategorija_id),
    CONSTRAINT fk_stavka_budzet FOREIGN KEY (budzet_id) REFERENCES budzeti(budzet_id),
    CONSTRAINT fk_stavka_kategorija FOREIGN KEY (kategorija_id) REFERENCES budzet_kategorije(kategorija_id),
    CONSTRAINT chk_stavka_iznosi CHECK (
        planirani_iznos >= 0 AND stvarni_iznos >= 0 AND prag_kriticnog > prag_upozorenja
    )
);

CREATE TABLE troskovi (
    trosak_id         NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    budzet_id         NUMBER(19) NOT NULL,
    kategorija_id     NUMBER(19) NOT NULL,
    opis              VARCHAR2(500),
    iznos             NUMBER(15,2) NOT NULL,
    refundirani_iznos NUMBER(15,2) DEFAULT 0 NOT NULL,
    tip_troska        VARCHAR2(32) DEFAULT 'RUCNI' NOT NULL,
    datum_troska      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_trosak_stavka FOREIGN KEY (budzet_id, kategorija_id)
        REFERENCES stavke_budzeta (budzet_id, kategorija_id),
    CONSTRAINT chk_trosak_iznosi CHECK (
        iznos >= 0 AND refundirani_iznos >= 0 AND refundirani_iznos <= iznos
    )
);

CREATE TABLE budzet_alert_log (
    log_id          NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    budzet_id       NUMBER(19) NOT NULL,
    kategorija_id   NUMBER(19) NOT NULL,
    kategorija_naziv VARCHAR2(255),
    alert_nivo      VARCHAR2(16) NOT NULL,
    ratio           NUMBER(7,4),
    poruka          VARCHAR2(500),
    kreirano_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

PROMPT === F3 tabele kreirane ===
